# This file is part of wsltty project

# Build image; of course wsltty has nothing to do with Visual Studio -
# this is just the name of Appveyor's build environment image
# that also contains cygwin
image: Visual Studio 2022

# Version format
version: "#{build}"

# Do not increment build number after pull requests
pull_requests:
  do_not_increment_build_number: true

# Do not start a new build when a new Git tag is created
skip_tags: true

init:
- cmd: |
    set PATH=C:\cygwin64;C:\cygwin64\bin;%windir%\System32
    setup-x86_64 -q -P unzip -P zoo -P patch -P lcab
    winget install Alpine

build_script:
- cmd: |
    make

test_script:
- cmd: |
    bin\mintty.exe --log mintty.log --exec echo hello mintty
    grep echo mintty.log
